services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/doeshing?schema=public
      DIRECT_URL: postgresql://postgres:postgres@db:5432/doeshing
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        "sh",
        "-c",
        "npm run prisma:migrate && npm run start"
      ]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doeshing
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
